DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;

CREATE TABLE user (
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE user_stock (
  username TEXT NOT NULL,
  stock_id INTEGER NOT NULL,
  FOREIGN KEY (username) REFERENCES user (username),
  FOREIGN KEY (stock_id) REFERENCES stock (stock_id)
);

CREATE TABLE stock (
  stock_id INTEGER PRIMARY KEY AUTOINCREMENT,
  stock_name TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
